z21_epic_main.sh: block propagation of $1
Currently a simple
```
singularity exec /cvmfs/eic.opensciencegrid.org/singularity/eicweb/eic_xl:26.07.1-stable eicrecon test.edm4hep.root
```
fails with
```
ERROR: file: /opt/software/linux-x86_64_v2/epic-26.07.1-uzwreubimqduvctpoysj5wmbj6ay5emu/share/epic/eicrecon.xml does not exist!
Check that your DETECTOR_PATH and DETECTOR_CONFIG environment variables are set correctly.
```
i.e. eicrecon is passed as $1 and is used by entrypoint.sh as the command to exec and by thisepic.sh to set 
DETECTOR_CONFIG.

This will source thisepic.sh in such a way that no detector config is set.